FROM openjdk:23-jdk

ARG DB_PASSWORD
ARG DB_USERNAME
ARG JWT_SECRET
ARG JWT_EXPIRATION

ENV DB_PASSWORD $DB_PASSWORD
ENV DB_USERNAME $DB_USERNAME
ENV JWT_SECRET $JWT_SECRET
ENV JWT_EXPIRATION $JWT_EXPIRATION

WORKDIR /app

COPY target/reservations-1.0-SNAPSHOT.jar /app/reservations-1.0.jar

EXPOSE 8081

ENTRYPOINT ["java","-jar","reservations-1.0.jar"]



