server:
  port: 8081


spring:
  application:
    name: reservation

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    username: admin
    url: jdbc:mysql://localhost:3306/java_training
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all=true:
